### ISSUE TITLE
invalid user/group

### ISSUE THREAD

**Issue by gregbert42** [boredazfcuk/docker-icloudpd#119]
Just pulled a new version. Now I am getting lots of errors like:

find: unknown user remote_fs_user

here is the log output: http://sprunge.us/mMVcq2

here is my docker-compose

```
services:
  iCloudPD:
    container_name: iCloudPD
    volumes:
      - /home/remote_fs_user/conf/icloudpd/usernamej:/config
      - /mnt/HDD/Archive/Pictures/iCloud_Sync/:/home/remote_fs_user/iCloud/
    environment:
      user: remote_fs_user
      user_id: 1002
      group: remote_fs_user
      group_id: 1002
      force_gid: True # also tried without this
      apple_id: usernamej@gmail.com
      authentication_type: 2FA
      synchronisation_interval: 21600
      TZ: Europe/Zurich
    image: 'boredazfcuk/icloudpd'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

```

any ideas? I feel like i struggled with this issue once before....
