### ISSUE TITLE
Synology Moments can NOT show photos after completed rebuild Index

### ISSUE THREAD

**Issue by tokyoqiang** [boredazfcuk/docker-icloudpd#147]
This is really a great code that helps me easily download photos from Icloud. 
My issue is synology moments can't show photos after it completed 'rebuild index'. If I move the photos to another location then move back, it can show.
I tried add User/UID/Group/Group ID predicate, it changed user from 1000 to my name, but still fail to show phto. 
![Snipaste_2022-03-18_14-36-29](https://user-images.githubusercontent.com/99979431/158950151-2ac7bef9-51ab-4223-8e0e-47017bd7cf86.jpg)

Can you help me to check the issue? Thanks!

**Comment by onestix** [comment]
Same issue here on a Synology DS918+ and Synology Photos. I am also using my own UID/GUID to upload these images.

**Comment by onestix** [comment]
I have been looking into this for the past 2 days now and I believe I have narrowed down the issue. It seems that Synology does not kickstart the indexing services (synofoto-bin-index-tool) and that specifically relates to docker volumes mapped to Synology volumes.. There are plenty of scripts/tools to actually tackle this problem, but I would ideally like to avoid running a separate indexing service on my NAS.

I did manage to find a clue on how the Synology indexing service can be initiated and that is via "touch" on the uploaded file itself, which worked for me and the image immediately appeared on the Synology Photos app - [see Reddit post here](https://www.reddit.com/r/synology/comments/lqewkg/comment/gogjd7v/?utm_source=share&utm_medium=web2x&context=3)

@tokyoqiang - can you give the following command a try? Do note that you need to run "touch" on the file itself and not on the folder:

`touch /volume1/PATH/TO/IMAGE/FILE.HEIC`

@boredazfcuk - I took a quick look at the code and it does not seem that a **touch** of the file is taking place for successful uploads. There are a few references to "_touch --reference="${heic_file}" "${heic_file%.HEIC}.JPG_", but these are only taking place for conversions it seems. Is this something you could introduce?

Thanks for your help!

**Comment by onestix** [comment]
@tokyoqiang - I have setup a temporary solution via the task scheduler. 

I enforce a file "touch" for files not older than a day in my specified volume. This triggers the indexing for newly added files.

Task scheduler -> Run command -> 'user defined scripts': 

```
#!/bin/bash
find /PATH/TO/FOLDER -mindepth 1 -mtime -1 ! -path '*/@eaDir*' ! -path '*/#recycle*' ! -path '*/#snapshot*' -execdir touch {} \;
```

Replace /PATH/TO/FOLDER with your own path that you wish to run the "touch" command on.  Make sure you to schedule the script to run daily or change the mtime value to something different, ie. -2. which in theory would search for files that have been added within the past two days.

@boredazfcuk - would still appreciate if you could consider my message above, because that would help our images appear instantly in our photos app.

Cheers

**Comment by boredazfcuk** [comment]
Hi,

When the files are downloaded, their date/time stamp is set to be the same date/time as the photo was taken. By touching the files after download, the date/time stamp is set to the current date/time. This will then cause a mismatch between the local file and the file stored in iCloud.

I've implemented a new variable `synology_photos_app_fix` which should touch the file twice, to trigger the re-index, but also set the date/time stamp back to the correct time.

I've not tested it, as I don't have a Synology device. Can you give it a try and let me know?

**Comment by onestix** [comment]
Thanks, mate. I wasn't aware that touch would change the date. Looks like I ruined my entire library :) I am starting from scratch and will keep you up to date!

Cheers

**Comment by onestix** [comment]
Hi @boredazfcuk, quick update. I downloaded my entire library again (appx 200gb) with the `synology_photos_app_fix` flag as active and it seems that the touch is taking place, however not reverting the date back to the original time/date. See below sample set of images taken in February:

![image](https://user-images.githubusercontent.com/84330001/163336650-073add95-902f-4729-adc9-37684a405efb.png)


I am using the following compose:

```
version: '3.3'
services:
    icloudpd:
        container_name: photobackup
        restart: always
        environment:
            - user=x
            - user_id=x
            - group=x
            - group_id=x
            - apple_id=x@x.com
            - authentication_type=2FA
            - 'folder_structure={:%Y/%m}'
            - notification_days=3
            - synchronisation_interval=21600
            - TZ=Europe/Amsterdam
            - 'download_path=/icloud'
            - notification_type=Webhook
            - notification_title="iCloud Photos"
            - skip_check=false
            - auto_delete=true
            - synology_photos_app_fix=true
        network_mode: host
        volumes:
            - '/volume1/docker/photobackup:/config'
            - '/volume1/homes/x/Photos/MobileBackup/x:/icloud'
        image: boredazfcuk/icloudpd:latest
```
