### ISSUE TITLE
Failsafe / .mounted Path Change / Multiple Install

### ISSUE THREAD

**Issue by Maniskryptus** [boredazfcuk/docker-icloudpd#202]
Hello,

I would like to install icloudpd as docker on my unraid server. That worked great. But since we are several people in the house, I need a 2 instance. However, the program always asks for the .mounted file in the iCloudpd folder, even though I renamed everything to iCloudpd_test. Is it possible to change the path of the failsafe file, .mounted? Original: /home/user/iCloud/.mounted Modified: /home/user/iCloud_test/.mounted. Thanks very much!

**Comment by fhandschuch** [comment]
I have three instances running each in it's own /path/to/docker/user1/, /path/to/docker/user2/ (called icloudpd-user1, icloudpd-user2 ...) with the according .mounted failsafe in the paths /path/to/user1/.mounted, /path/to/user2/.mounted ...
That works fine for me.

**Comment by Maniskryptus** [comment]
Hi, ich glaube du kannst auch Deutsch, oder? 

Ich würde gerne deine Vorgehensweise probieren, kannst du mir das etwas genauer erklären? 
Wo muss ich den Pfad denn so eingeben das es passt? 

Vielen Dank!

**Comment by fhandschuch** [comment]
multilingual reply so that others may follow too ;)

Vorbemerkung: Docker auf Synology NAS mit docker-compose.yml Dateien (statt Synology Docker GUI)
Preliminary remark: Docker on Synology NAS with docker-compose.yml files (instead of Synology Docker GUI)

Pfade:
Docker Konfigurationen /volume1/docker/icloudpd-userX/
Benutzerordner /volume1/homes/userX/iCloudPhotoDownload/
Paths:
Docker configurations /volume1/docker/icloudpd-userX/
user folders /volume1/homes/userX/iCloudPhotoDownload/

docker-compose.yml:
```
version: "2.4"
services:
   icloudpd-userX:
      hostname: synology
      container_name: icloudpd-userX
      env_file:
         - /volume1/docker/icloudpd-userX/example.env
      environment:
         - TZ=Europe/Berlin

      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         interval: 1m
         timeout: 10s
         retries: 3
         start_period: 40s
      restart: unless-stopped
      volumes:
         - /volume1/docker/icloudpd-userX:/config
         - /volume1/homes/userX/iCloudPhotoDownload/:/home/userX/iCloud/
```

**Comment by eliempje** [comment]
The basic of a docker container is that is has its one file system for each container.
You can mount a volume/folder of the host to be available in a container.
There is our solution: mount two different folders on the host to two different containers.

**Comment by Maniskryptus** [comment]
Hello,

thank you for the answers. However, I understand the solutions only related to the standard Docker environments, and not to the environment related to UNRAID.

With UNRAID I unfortunately don't have the possibility to proceed as written here. No matter which path I specify manually, it always wants to make the failsafe under /iCloud/ instead of under iCloud_userx/. Of course that doesn't work.

Is there a solution for the UNRAID icloudpd version?

**Comment by boredazfcuk** [comment]
Hi,

The failsafe will always be created under /iCloud. That part of the path is hardcoded and never changes.

The part of the path that does change is determined by the *user* variable.

So your example should look like this instead:

>Original: /home/user/iCloud/.mounted Modified: /home/user_test/iCloud/.mounted

I should probably have posted an example `icloudpd_*.env` file, here's something very similar to mine:

```
user=boredazfcuk
user_id=1000
group=admins
group_id=1010

apple_id=notappnin@email.com

folder_structure={:%Y/%m}

auto_delete=True

skip_check=True

synchronisation_interval=21600

convert_heic_to_jpeg=True
jpeg_quality=100

delete_accompanying=True

delete_empty_directories=True

notification_days=14

notification_title=iCloudPD

notification_type=Telegram

telegram_token=wf7gwesomerandomestufaaaaahhhhhh23498y3f
telegram_chat_id=999666888
telegram_silent_file_notifications=true
```
>Is there a solution for the UNRAID icloudpd version?

There is no specific UNRAID version.

I'm aware that there is a "template" for Docker UNRAID (whatever that is), as I stumbled upon this (https://forums.unraid.net/topic/88159-icloud-picture-downloader-docker-template/) a couple of years ago. What that template does, (and if it hard-codes the `/home/user/icloud/` part), I couldn't say, as I don't have any experience with UNRAID. Maybe it's a problem with the template.

**Comment by boredazfcuk** [comment]
It's also worth pointing out that the `user` variable is only really needed for adjusting permissions. The container doesn't really care whether the user variable is passed or not.

The important part is the mount information which you are creating your container with. When working with volume entries the first part is the location where the files exist on your server, the second is where that folder exists inside the container.

```
      volumes:
         - icloudpd_ipad_config:/config
         - /home/ipad/iCloud:/home/user/iCloud
...
      volumes:
         - icloudpd_boredazfcuk_config:/config
         - /home/boredazfcuk/iCloud:/home/user/iCloud
...
      volumes:
         - icloudpd_kida_config:/config
         - /home/kida/iCloud:/home/user/iCloud
...
      volumes:
         - icloudpd_mrs_config:/config
         - /home/mrs/iCloud:/home/user/iCloud
```
