### ISSUE TITLE
Changing default environment variables?

### ISSUE THREAD

**Issue by soti11** [boredazfcuk/docker-icloudpd#217]
How can I change the default environment variables.
I would like to change the folder_structure to none, but dont know how to do this

**Comment by boredazfcuk** [comment]
Hi,

How you set variables depends entirely on the platform you are creating the container in.
You just set the `folder_structure` variable in the same way you would set your `apple_id` variable.

If creating docker container from the Linux command line, you would just use something like this:
```
docker create \
   --name iCloudPD_boredazfcuk \
   --hostname icloudpd_boredazfcuk \
   --network icloudpd_bridge \
   --restart=always \
   --env user=boredazfcuk \
   --env user_id=1000 \
   --env group=admins \
   --env group_id=1010 \
   --env apple_id=notmy@email.com \
   --env authentication_type=2FA \
   --env notification_type=Telegram \
   --env telegram_token=123654 \
   --env telegram_chat_id=456321 \
   --env folder_structure=none \
   --env auto_delete=True \
   --env notification_days=14 \
   --env synchronisation_interval=21600 \
   --env TZ=Europe/London \
   --volume icloudpd_boredazfcuk_config:/config \
   --volume /home/boredazfcuk/iCloud:/home/boredazfcuk/iCloud \
   boredazfcuk/icloudpd
```

Or if using docker-compose, the docker-compose.yaml file would resemble this:
```
version: "3.8"

volumes:
   config:
      name: icloudpd_config

services:
   icloudpd:
      hostname: icloudpd
      env_file:
         - example.env
      environment:
         - TZ=Europe/London
         - folder_structure=none
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - config:/config
         - ./iCloud/:/home/${user}/iCloud/
```

Thanks.
