### ISSUE TITLE
Permissions Issue and unknown/invalid user

### ISSUE THREAD

**Issue by robflate** [boredazfcuk/docker-icloudpd#23]
If I run the container with the following docker-compose file, I get permissions errors. The user, user_id, group and group_id are the same as on the host. If I correct the local permissions with chown to match the docker-compose file, I still get permission errors.

If I run `docker exec -it icloudpd /usr/local/bin/sync-icloud.sh`, the script runs through without any interaction and says the 2FA cookie has been set but it is not.

**docker-compose;**
```
  icloudpd:
    container_name: icloudpd
    image: boredazfcuk/icloudpd
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /home/mint/Docker/media-server/config/icloudpd:/config
      - /media/mint/htpc09/Media/Photos/iCloud:/home/mint/iCloud
    environment:
      user: mint
      user_id: 501
      group: docker
      group_id: 999
      apple_id: xxxx@xxxx.com
      apple_password: "usekeyring"
      authentication_type: "2FA"
      notification_days: 14
      command_line_options: '--folder-structure={:%Y} --recent 50 --auto-delete'
      synchronisation_interval: 21600
      TZ: Europe/London
```
The only way I could get the 2FA cookie was to run the above docker-compose without the user, user_id, group and group_id env variables, so instead it uses the defaults. I was then able to run the `docker exec` command and successfully get the 2FA cookie. After this I reinstated the user, user_id, group and group_id env variables and chown the local folders to match. This results in the following log but no photos are downloaded;

**logs**
```
today at 21:32 2020-08-22 21:32:00 INFO     Group ID available, creating group
today at 21:32 addgroup: gid '999' in use
today at 21:32 2020-08-22 21:32:00 INFO     User ID available, creating user
today at 21:32 adduser: unknown group docker
today at 21:32 2020-08-22 21:32:00 INFO     Correct owner on config directory, if required
today at 21:32 find: unknown user mint
today at 21:32 2020-08-22 21:32:00 INFO     Correct group on config directory, if required
today at 21:32 find: unknown group docker
today at 21:32 2020-08-22 21:32:00 INFO     Using password stored in keyring
today at 21:32 2020-08-22 21:32:00 INFO     Set owner, mint, on iCloud directory, if required
today at 21:32 find: unknown user mint
today at 21:32 2020-08-22 21:32:00 INFO     Set group, docker, on iCloud directory, if required
today at 21:32 find: unknown group docker
today at 21:32 2020-08-22 21:32:00 INFO     Correct owner on icloudpd temp directory, if required
today at 21:32 find: unknown user mint
today at 21:32 2020-08-22 21:32:00 INFO     Correct group on icloudpd temp directory, if required
today at 21:32 find: unknown group docker
today at 21:32 2020-08-22 21:32:00 INFO     Correct owner on config directory, if required
today at 21:32 find: unknown user mint
today at 21:32 2020-08-22 21:32:00 INFO     Correct group on config directory, if required
today at 21:32 find: unknown group docker
today at 21:32 2020-08-22 21:32:00 INFO     Correct owner on keyring directory, if required
today at 21:32 find: unknown user mint
today at 21:32 2020-08-22 21:32:00 INFO     Correct group on keyring directory, if required
today at 21:32 find: unknown group docker
today at 21:32 2020-08-22 21:32:00 INFO     Set 750 permissions on iCloud directories, if required
today at 21:32 2020-08-22 21:32:00 INFO     Set 640 permissions on iCloud files, if required
today at 21:32 2020-08-22 21:32:00 INFO     Sync user mint
today at 21:32 chown: invalid user: ‘mint:docker’
today at 21:32 2020-08-22 21:32:00 INFO     Check 2FA Cookie
today at 21:32 2020-08-22 21:32:00 INFO     Cookie exists, check expiry date
today at 21:32 2020-08-22 21:32:00 INFO     Valid two factor authentication cookie found. Days until expiration: 89
today at 21:32 2020-08-22 21:32:00 INFO     Check download directory mounted correctly
today at 21:32 2020-08-22 21:32:00 INFO     Check for new files using password stored in keyring...
today at 21:32 su: unknown user mint
today at 21:32 cat: /tmp/icloudpd/icloud_check_exit_code: No such file or directory
today at 21:32 ash: out of range
today at 21:32 2020-08-22 21:32:00 INFO     Check successful
today at 21:32 grep: /tmp/icloudpd/icloudpd_check.log: No such file or directory
today at 21:32 ash: out of range
today at 21:32 ash: out of range
today at 21:32 2020-08-22 21:32:00 INFO     No new files detected. Nothing to download
today at 21:32 ash: out of range
today at 21:32 2020-08-22 21:32:00 INFO     Web cookie expires: 2020-10-21 @ 20:24:44
today at 21:32 2020-08-22 21:32:00 INFO     Two factor authentication cookie expires: 2020-11-20 @ 20:25:06
today at 21:32 2020-08-22 21:32:00 INFO     Next syncronisation at 03:32
```

I'm not sure if it is relevant but if I `docker exec` into the container and run `ls -l` it shows the /config folder has permissions of `mint:ping`. The user:group I set in the env variables is `mint:docker`.

Any advice appreciated. Thanks.
