### ISSUE TITLE
jpeg path

### ISSUE THREAD

**Issue by eded9698** [boredazfcuk/docker-icloudpd#439]
How do I set the jpeg path?  I have it set to "/mnt/user/home media/pictures/jpeg" using unraid.  The log show it is converting the files to the folder but nothing is in the folder.

**Comment by boredazfcuk** [comment]
You will also need to mount the folder to the same location inside the container.

Something like this:
```
   icloudpd_user1:
      hostname: icloudpd_user1
      container_name: icloudpd_user1
      networks:
         - containers
      environment:
         - TZ=Europe/London
         - jpeg_path=/mnt/user/home media/pictures/jpeg
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - icloudpd_user1_config:/config/
         - /mnt/hd1/icloudpd/user1/iCloud/:/home/user1/iCloud/
         - /mnt/user/home media/pictures/jpeg:/mnt/user/home media/pictures/jpeg
 ```
