### ISSUE TITLE
Crashing when downloading a video file

### ISSUE THREAD

**Issue by sbogomolov** [boredazfcuk/docker-icloudpd#450]
I have setup three identical deployments with `icloudpd` for three different icloud accounts. One of them worked flawlessly, the other two keep crashing. One of them is crashing every time it tries to download the same video file:
```
...
2023-12-16 13:53:19 DEBUG    /photo/2021/12/18/IMG_1178.MOV already exists
2023-12-16 13:53:19 DEBUG    /photo/2021/12/18/IMG_1177.JPG already exists
2023-12-16 13:53:19 DEBUG    Downloading /photo/2021/11/28/IMG_1093.MOV...
Stream closed EOF for icloudpd/icloudpd-574f47bc69-gxljs (icloudpd)
```

It hangs there for a while trying to download it, then container crashes, restarts and repeats this all over again. Is there something I can try to fix this?

I'm using the latest docker image tag `1.0.685`. My settings are as follows:
```yaml
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: apple_id
          value: xxxxxxxxxxxxxxxxxxxx
        - name: user
          value: icloudpd
        - name: user_id
          value: '1014'
        - name: group
          value: icloudpd
        - name: group_id
          value: '1014'
        - name: download_path
          value: /photo
        - name: synchronisation_interval
          value: '86400'
        - name: synchronisation_delay
          value: '0'
        - name: skip_check
          value: 'false'
        - name: notification_type
          value: Discord
        - name: notification_title
          value: icloudpd
        - name: discord_id
          valueFrom:
            secretKeyRef:
              name: icloudpd
              key: discord-id
        - name: discord_token
          valueFrom:
            secretKeyRef:
              name: icloudpd
              key: discord-token
```
