### ISSUE TITLE
/config/icloudpd.conf: line 22: {:%Y/%m/%d}: not found

### ISSUE THREAD

**Issue by rustig136** [boredazfcuk/docker-icloudpd#488]
Hi, it must be something simple but I can't figure out why /config/icloudpd.conf can't be found.
The application updates/stores the running config in the 'config' location '/home/pi/appdata/etc/icloudpd/icloudpd_config' and everything seems to be running fine.

Can you help me remove this error, please?

Thanks!
M

pi@docker:~/appdata/etc/icloudpd $ docker-compose logs
Attaching to icloudpd
icloudpd    | 
icloudpd    | 2024-01-14 19:13:31 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.714 started *****
icloudpd    | 2024-01-14 19:13:31 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
icloudpd    | 2024-01-14 19:13:31 INFO     Alpine Linux 3.19.0
icloudpd    | 2024-01-14 19:13:31 INFO     Python version: 3.11.6
icloudpd    | 2024-01-14 19:13:31 INFO     Loading configuration from: /config/icloudpd.conf

**icloudpd    | /usr/local/bin/sync-icloud.sh: /config/icloudpd.conf: line 22: {:%Y/%m/%d}: not found**

icloudpd    | 2024-01-14 19:13:31 INFO     Apple ID: xxx
icloudpd    | 2024-01-14 19:13:31 INFO     Authentication Type: MFA
icloudpd    | 2024-01-14 19:13:31 INFO     Cookie path: /config/xxx
icloudpd    | 2024-01-14 19:13:31 INFO     Cookie expiry notification period: 7
icloudpd    | 2024-01-14 19:13:31 INFO     Download destination directory: /home/xxx/iCloud/
icloudpd    | 2024-01-14 19:13:31 INFO     Folder structure:  {:%Y/%m/%d}
icloudpd    | 2024-01-14 19:13:31 INFO     Synchronisation interval: 43200
icloudpd    | 2024-01-14 19:13:31 INFO     Synchronisation delay (minutes): 0
icloudpd    | 2024-01-14 19:13:31 INFO     Set EXIF date/time: false
icloudpd    | 2024-01-14 19:13:31 INFO     Auto delete: false
icloudpd    | 2024-01-14 19:13:31 INFO     Delete after download: false
icloudpd    | 2024-01-14 19:13:31 INFO     Photo size: original
icloudpd    | 2024-01-14 19:13:31 INFO     Single pass mode: false
icloudpd    | 2024-01-14 19:13:31 INFO     Skip download check: false
icloudpd    | 2024-01-14 19:13:31 INFO     Skip live photos: false
icloudpd    | 2024-01-14 19:13:31 INFO     Number of most recently added photos to download: Download All Photos
icloudpd    | 2024-01-14 19:13:31 INFO     Downloading photos from: Download All Photos
icloudpd    | 2024-01-14 19:13:31 INFO     Stop downloading when prexisiting files count is: Download All Photos
icloudpd    | 2024-01-14 19:13:31 INFO     Live photo size: original
icloudpd    | 2024-01-14 19:13:31 INFO     Skip videos: false
icloudpd    | 2024-01-14 19:13:31 INFO     Convert HEIC to JPEG: true
icloudpd    | 2024-01-14 19:13:31 INFO     Pushover notifications enabled
icloudpd    | 2024-01-14 19:13:31 INFO     Pushover user: xxx
icloudpd    | 2024-01-14 19:13:31 INFO     Pushover token: xxx
icloudpd    | 2024-01-14 19:13:31 INFO     Sending Pushover startup notification
icloudpd    | 2024-01-14 19:13:32 INFO     Downloading from: icloud.com
icloudpd    | 2024-01-14 19:13:32 INFO     Authentication domain: com
icloudpd    | 2024-01-14 19:13:32 INFO     Ignore Synology extended attribute directories: Disabled
icloudpd    | 2024-01-14 19:13:34 INFO     Directory is writable: /config/python_keyring/
icloudpd    | 2024-01-14 19:13:34 INFO     Check download directory mounted correctly...
icloudpd    | 2024-01-14 19:13:34 INFO     Failsafe file /home/xxx/iCloud//.mounted exists, continuing
icloudpd    | 2024-01-14 19:13:34 INFO     Directory is writable: /config/python_keyring/
icloudpd    | 2024-01-14 19:13:34 INFO     Keyring file exists, continuing
icloudpd    | 2024-01-14 19:13:34 INFO     Sync user: xxx
icloudpd    | 2024-01-14 19:13:34 INFO     Synchronisation starting at 19:13:34
icloudpd    | 2024-01-14 19:13:34 INFO     Keyring file exists, continuing
icloudpd    | 2024-01-14 19:13:34 INFO     Check download directory mounted correctly...
icloudpd    | 2024-01-14 19:13:34 INFO     Failsafe file /home/xxx/iCloud//.mounted exists, continuing
icloudpd    | 2024-01-14 19:13:34 INFO     Check for new files using password stored in keyring file
icloudpd    | 2024-01-14 19:13:34 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time

------

```
_Docker-compose.yml_

version: "3.8"

volumes:
   config:
     name: icloudpd_config

services:
   icloudpd:
      container_name: icloudpd
      hostname: icloudpd_xxx
      environment:
         - apple_id=xxx
         - user=xxx
         - user_id=1000
         - group=group
         - group_id=1000
         - TZ=Europe/Amsterdam
         - download_path=/home/xxx/iCloud/
         - synchronisation_interval=43200
         - synchronisation_delay=0
         - notification_days=7
         - authentication_type=MFA
         - directory_permissions=750
         - file_permissions=640
         - folder_structure= {:%Y/%m/%d}
         - skip_check=false
         - download_notifications=true
         - delete_notifications=true
         - startup_notification=true
         - convert_heic_to_jpeg=true
         - notification_type=Pushover
         - notification_title=iCloudPD
         - pushover_user=xxx
         - pushover_token=xxx
         
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
#       - config:/home/pi/appdata/etc/icloudpd/icloudpd_config          # dit not help :(
         - /home/pi/appdata/etc/icloudpd/icloudpd_config:/config
         - /mnt/backup/icloud:/home/xxx/
```
