### ISSUE TITLE
Download directory not mapping correctly - docker-compose

### ISSUE THREAD

**Issue by chris948** [boredazfcuk/docker-icloudpd#49]
Apologize if this is expected or I'm misunderstanding it, but this doesn't make sense to me.

1. Trying to use docker compose, filled out the .env file.
Using the .env file "user=chris" and docker compose with "icloud_backup:/home/${user}/iCloud/" (it's slightly longer, but my folder location on the left side is irrelevant here) when I remote into the container, there are two directories in home.

iCloud
chris

iCloud is mapped to my volume, I confirmed this logging into the container and going to /home/iCloud and executing "touch test123" which is now a file exposed to my server in the "icloud_backup" directory. /home/chris is empty. Obviously I get the error ".mounted file is not present. " 

2. I changed my docker compose to include the user:
        environment:
            - TZ=${TZ}
            - user=chris
       volumes:
            - ~/docker/utilities/icloudpd/config:/config
            - icloud_backup:/home/${user}/iCloud/
            -
Same folders, same problem. My volume is mapping to "iCloud"

iCloud
chris

The problem is, the volume is still mapping to /home/iCloud. So the script is checking the correct place, " while [ ! -f "${download_path}/.mounted" ]; do" which corresponds to /home/chris/iCloud, but my volume is mapped to /home/iCloud

I'm afraid to try to continue. If the backup works, I assume it will fill the container, and not my volume like it should.

Trying to make a long story short. Volume is mapping to /home/iCloud, expected behavior is /home/chris/iCloud and I don't know enough about docker to find out what it's doing with that volume entry.

thank you,
Chris

**Comment by boredazfcuk** [comment]
Hi,
The `environment:` section in docker-compose is to list variables that are made available inside the Docker container. The compose file itself is not aware of them unfortunately.

You will need to change your compose file to:
```
environment:
  - TZ=${TZ}
  - user=chris
volumes:
  - ~/docker/utilities/icloudpd/config:/config
  - icloud_backup:/home/chris/iCloud/
```

Thanks.

**Comment by chris948** [comment]
Thanks for the reply. I really appreciate your time and the chance to learn something here. I'm trying to find out where/how that volume is mapped in docker, but that's over my head right now. If I need to be more descriptive, please let me know.

I can confirm that setting environment in the compose, or icloudpd.env is does the same thing. I just rebuilt it using the .env.


compose file:
```
    icloudpd:
        hostname: icloudpd
        container_name: icloudpd
        env_file:
            - icloudpd.env
        environment:
            - TZ=${TZ}
#            - user=chris
        image: boredazfcuk/icloudpd
        healthcheck:
            test: /usr/local/bin/healthcheck.sh
            start_period: 30s
        restart: always
        volumes:
            - ~/docker/utilities/icloudpd/config:/config
            - /zfs_mirror/pictures/icloud_backup:/home/${user}/iCloud/
```

         
.env file
```
# iCloudPD environment variables
# Variables with values beneath are showing the defaults used by the script if not specified

# User and group details for account
user=chris
user_id=1000
group=root
group_id=0
```
It's taking the user in both cases, the issue is the volume is mapping to /user/iCloud. I don't think this is right. Why is it even creating an iCloud user? And certainly my files shouldn't be going there should they? Your script is checking for a .mounted in /home/chris

> / # cd /home
> /home # ls
> chris  iCloud
> /home # cd iCloud
> /home/iCloud # ls
> test2.txt
> /home/iCloud # cd ../chris
> /home/chris # ls
> /home/chris # 


in my box: 

> chris@odroid-nas:/zfs_mirror/pictures/icloud_backup$ ls
> test2.txt

But obviously I get

2020-12-16 08:13:13 INFO     Check download directory mounted correctly


> 2020-12-16 08:13:13 ERROR    Failsafe file /home/chris/iCloud/.mounted file is not present. Plese check the host's target volume is mounted - retry in 5 minutes

The TZ in curlys is set in an env variable so I only set it on the machine and save myself time. I too have quite a few variables in 6 compose files and ~30 containers. It's working perfectly. Your excellent logging confirms it.

2020-12-16 08:12:58 INFO     Time zone: America/Chicago
