### ISSUE TITLE
Bark startup notification failed with http status code: 000 and curl exit code: 6

### ISSUE THREAD

**Issue by mhqschen** [boredazfcuk/docker-icloudpd#528]
Logs:
```
2024-03-22 13:30:38 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.718 started *****
2024-03-22 13:30:38 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
……
2024-03-22 13:31:01 INFO     Bark notifications enabled
2024-03-22 13:31:01 INFO     Bark device key: xxxxxxxx
2024-03-22 13:31:01 INFO     Bark server: https://api.day.app:443
2024-03-22 13:31:01 INFO     Sending Bark startup notification
2024-03-22 13:31:01 ERROR    Bark startup notification failed with http status code: 000 and curl exit code: 6
```

Settings:
```
bark_device_key="xxxxxxxx"
bark_server="https://api.day.app:443"
notification_type=Bark
```

Attach the container and run curl:
```
# curl https://api.day.app/xxxxxxxx/test
{"code":200,"message":"success","timestamp":1711085706}/
```

**Comment by Arnold4869** [comment]
我之前配置的时候使用域名不行，使用192.168开头的内网ip可以

**Comment by boredazfcuk** [comment]
curl exit code 6 is "host not found"

**Comment by mhqschen** [comment]
> curl exit code 6 is "host not found" The :443 should be unnecessary when using https:// prefix. Try removing that so the configuration in the container is the same as your test from the command line.

No luck.
I've tried both below two kind of settings. Got same error message.
```
bark_server="https://api.day.app/"
bark_server="https://api.day.app"
```

```
2024-04-03 10:54:31 INFO     Bark notifications enabled
2024-04-03 10:54:31 INFO     Bark device key: XXXXXX
2024-04-03 10:54:31 INFO     Bark server: https://api.day.app
2024-04-03 10:54:31 INFO     Sending Bark startup notification
2024-04-03 10:54:31 ERROR    Bark startup notification failed with http status code: 000 and curl exit code: 6
2024-04-03 10:54:31 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
```

**Comment by mhqschen** [comment]
Here's my docker compose file, should has nothing related with this error.

```
version: '3.3'
services:
    icloudpd:
        container_name: icloudpd
        network_mode: bridge
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - '/xxx/icloudpd/config:/config'
            - '/xxxxx:/home/user/iCloud'
        image: boredazfcuk/icloudpd
```

**Comment by mhqschen** [comment]
> You've not created a network for the container. Try that:
> 
> https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md#creating-a-container

Thanks for the hint. I've directly used the code in this file to create a network.
```
docker network create \
   --driver=bridge \
   --subnet=192.168.115.0/24 \
   --gateway=192.168.115.254 \
   --opt com.docker.network.bridge.name=icloudpd_br0 \
   icloudpd_bridge
```

And then modified the docker compose file to use this network.
```
version: '3.3'
services:
    icloudpd:
        container_name: icloudpd
        networks:
            - icloudpd_bridge
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - '/xxx/icloudpd/config:/config'
            - '/xxxxx:/home/user/iCloud'
        image: boredazfcuk/icloudpd
networks:
    icloudpd_bridge:
        external: true
        name: icloudpd_bridge          
```

Can confirm that the container is using the network.
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/9138710/8df0623d-5140-4902-b9a8-ffdaaf7030fd)

The DNS failed totally, can't find host even when attach the container.

After adding the DNS info, the problem back to before( Can curl when attaching but get code 6 by icloudpd itself).
```
    dns:
      - 223.5.5.5
```

**Comment by boredazfcuk** [comment]
I create mine with a single docker-compose.yml like this:
```
version: "3.7"

networks:
   containers:
      name: containers
      external: true
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 192.168.99.0/24
      driver_opts:
         com.docker.network.bridge.name: containers0

volumes:
   icloudpd_boredazfcuk_config:
      name: icloudpd_boredazfcuk_config

 icloudpd_boredazfcuk:
    hostname: icloudpd_boredazfcuk
    container_name: icloudpd_boredazfcuk
    networks:
       - containers
    environment:
       - TZ=Europe/London
    image: boredazfcuk/icloudpd
    healthcheck:
       test: /usr/local/bin/healthcheck.sh
       start_period: 630s
    restart: always
    volumes:
       - icloudpd_boredazfcuk_config:/config/
       - /mnt/icloudpd/boredazfcuk/iCloud:/home/boredazfcuk/iCloud/
```

DNS works fine. What version of Docker are you using? It should be listed on the Portainer home page.
