### ISSUE TITLE
IOError SMB share from Truenas

### ISSUE THREAD

**Issue by JasSuri** [boredazfcuk/docker-icloudpd#664]
**Describe the bug**
I have setup Truenas to expose the folder `/mnt/files/media/photos/icloud_photos` via SMB.
I have setup kubernetes (k3s) to run icloudpd as a pod. Everything works OK when using an NFS share. But when using the SMB share, I get the error: 

```
2024-10-11 13:58:38 INFO     Failsafe file /photos/.mounted exists, continuing
2024-10-11 13:58:42 INFO     Downloading 9334 original photos and videos to /photos ...
2024-10-11 13:58:45 ERROR    IOError while writing file to /photos/2024/10/IMG_0619.MOV. You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
```

Here is my k3s deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: icloudpd
  name: icloudpd
  namespace: icloudpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icloudpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: icloudpd
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/London
            - name: authentication_type
              value: 2FA
            - name: auto_delete
              value: "false"
            - name: convert_heic_to_jpeg
              value: "false"
            - name: download_path
              value: '/photos'
            - name: folder_structure
              value: '{:%Y/%m}'
            - name: group
              value: jas
            - name: group_id
              value: "3000"
            - name: notification_days
              value: "7"
            - name: skip_check
              value: "true"
            - name: synchronisation_interval
              value: "21600"
            - name: user
              value: jas
            - name: user_id
              value: "3000"
          image: boredazfcuk/icloudpd:latest
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 600
            timeoutSeconds: 10
          name: icloudpd
          volumeMounts:
            - mountPath: /config
              name: icloudpd-config
              subPath: config
            - mountPath: /photos
              name: icloudpd-photos
              subPath: icloud_photos
      restartPolicy: Always
      volumes:
        - name: icloudpd-config
          persistentVolumeClaim:
            claimName: icloudpd-config-pvc
        - name: icloudpd-photos
          persistentVolumeClaim:
            claimName: icloudpd-photos-pvc
```

Here is my k3s volume config:

```
apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
  namespace: icloudpd
type: Opaque
stringData:
  username: "jas"
  password: "abcdef"


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: newsmb
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.27/Files/Media/Photos"
  csi.storage.k8s.io/node-publish-secret-name: "smb-creds"
  csi.storage.k8s.io/node-publish-secret-namespace: "icloudpd"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: photos-pv
  labels:
    app: icloudpd
spec:
  capacity:
    storage: 300Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: newsmb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: photos-pv
    volumeAttributes:
      source: "//192.168.1.27/Files/Media/Photos"
    nodeStageSecretRef:
      name: smb-creds
      namespace: icloudpd

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: icloudpd-photos-pvc
  namespace: icloudpd
  labels:
    app: icloudpd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi  # Match or be less than the PV's capacity
  volumeName: photos-pv # Bind explicitly to the PV created above
  storageClassName: 'newsmb'

```

When I remote into the pod, I can cd `/photos` and see the contents of my photos folder.
I can `touch /photos/test` and see the file `test` on the share via another server. It seems the pod can RW to the folder, but the icloudpd service can only ?read? to the directory, as it seems to find the `.mounted` file, and other files that already exist as part of the download process.

**Expected behaviour**
Be able to RW to the smb share.

**System (please complete the following information):**
 - OS: Debian
 - Version 12

**Debug log file**
[icloudpd_log.txt](https://github.com/user-attachments/files/17343184/icloudpd_log.txt)

**Comment by JasSuri** [comment]
I tried the smb example pod and this can write to the same volume config, which icloudpd cannot.

https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-smb
  namespace: icloudpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-smb
    spec:
      containers:
        - name: deployment-smb
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/smb/outfile; sleep 1; done
          volumeMounts:
            - name: smb
              mountPath: "/mnt/smb"
              readOnly: false
              subPath: icloud_photos
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: icloudpd-photos-pvc
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

**Comment by boredazfcuk** [comment]
https://github.com/boredazfcuk/docker-icloudpd/issues/376

The person who reported this issue before fixed it by setting the permissions to 777, so it's likely that there is a user/permissions error somewhere along the lines.

**Comment by jasjeetsuri** [comment]
My ACL on Truenas has jas as owner and group on the root folder. And permission applied recursively. It’s UID 3000 and GID 3000.

On the SMB driver, I’m using 3000 uid and 3000 gid.

In the deployment for iCloudpd, I’m using user: jas, group: jas. UID 3000, gid 3000.

In the container, the config folder is 3000:3000, but the smb mount is root:root.

Im not sure where to look next. I cant chmod files on an SMB share in truenas, instead it’s controlled by the ACL.

**Comment by boredazfcuk** [comment]
https://forums.docker.com/t/a-workaround-for-net-writing-to-cifs-volume-yielding-empty-file-and-access-to-the-path-is-denied/110872

Try adding the `nobrl` option to the mount command

**Comment by JasSuri** [comment]
Ok I managed to make it work. It was a few things
1. Wrong ACL on the SMB share
2. I was using the same PV name as another PV so my settings were not taking effect..

ACL settings
![image](https://github.com/user-attachments/assets/0d837c02-1546-4215-ab64-5f611c85a64e)

![image](https://github.com/user-attachments/assets/f11f73f8-3d3e-4afc-9b27-87b37056ce6a)

PV
```
apiVersion: v1
kind: Secret
metadata:
  name: smb-creds2
  namespace: icloudpd
type: Opaque
stringData:
  username: "jas"
  password: "password"


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: newsmb2
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.27/Files/Media/Photos"
  csi.storage.k8s.io/node-publish-secret-name: "smb-creds2"
  csi.storage.k8s.io/node-publish-secret-namespace: "icloudpd"
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=3000
  - gid=3000
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: icloud-photos-pv1
  labels:
    app: icloudpd
spec:
  capacity:
    storage: 300Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: newsmb2
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=3000
    - gid=3000
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: icloud-photos-pv1
    volumeAttributes:
      source: "//192.168.1.27/Files/Media/Photos"
    nodeStageSecretRef:
      name: smb-creds2
      namespace: icloudpd
```

PVC

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: icloudpd-photos-pvc2
  namespace: icloudpd
  labels:
    app: icloudpd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi  # Match or be less than the PV's capacity
  volumeName: icloud-photos-pv1 # Bind explicitly to the PV created above
  storageClassName: 'newsmb2'
```
