### ISSUE TITLE
ERROR    Could not create folder /home/user/iCloud/****

### ISSUE THREAD

**Issue by filikun** [boredazfcuk/docker-icloudpd#689]
**Describe the bug**
I'm trying to set this up for the first time. I had a hard time getting the auth and stuff to work. It was some trial and error before getting to this point but here I'm stuck. 

I figure it is a permission problem. So I hopped on the docker host and made a new user = userid 1000, gave the folder '/var/lib/docker/volumes/icloudpd_icloudpd-smb/_data' ```chown -r 1000:1000```, ```chmod -R 755``` and with that user then tried to create a folder and that worked. I searched far and wide for a solution but could not find any. icloudpd-smb is on my NAS (an old readyNAS).

***Portainer stack***

```
version: "3.8"
services:
   icloudpd_filip:
      hostname: icloudpd_filip
      environment:
         - TZ=Europe/Stockholm
      env_file:
        - stack.env
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - icloudpd_config:/config
         - icloudpd-smb:/home/user/iCloud
volumes:
  icloudpd-smb:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=Icloudpd,password=PASSWORD,vers=3.0,rw"
      device: "//10.0.50.200/Icloudpd"
  icloudpd_config:
    name: icloudpd_config
``` 

***Environment variables***
```
apple_id: name@lastname.se
authentication_type: 2FA
folder_structure: "{:%Y-%m-%d}"
synchronisation_interval: 86400
directory_permissions: 755
file_permissions: 644
user_id: 1000
group_id: 1000
```

**Expected behaviour**
Download my photos.

**Actual behaviour**
Can't create folders, probably permission issues

**System (The following information must be entered or the issue will be closed):**
 - OS: Debian
 - Version: 12
 - Proxmox 8.2.2
 - Running docker in an LXC
 - Docker standalone 24.0.7
 - Portainer 2.19.5

**Debug log file**
[log.txt](https://github.com/user-attachments/files/17645243/log.txt)
