### ISSUE TITLE
/usr/local/bin/sync-icloud.sh: line 1724: syntax error: unexpected "fi" (expecting "done")

### ISSUE THREAD

**Issue by lazerdave** [boredazfcuk/docker-icloudpd#765]
**System:**
 - OS: unRAID
 - Version: 7.0.0
 
**Describe the bug**
After creating a new Docker Compose (below), unable to run sync-icloud.sh.

```
networks:
   icloudpd:
      name: icloudpd
      driver: bridge
      ipam:
         driver: default
      driver_opts:
         com.docker.network.bridge.name: icloudpd

volumes:
   icloudpd_user1_config:
      name: icloudpd_user1_config
   icloudpd_user2_config:
      name: icloudpd_user2_config

services:
   icloudpd_user1:
      hostname: icloudpd_user1
      networks:
         icloudpd:
            aliases:
               - icloudpd_user1
      environment:
         - TZ=America/Denver
         - user=***REDACTED-user1'sAppleID***
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - icloudpd_user1_config:/mnt/user/appdata/icloudpd-***REDACTED-user1'sInitials***
         - ./iCloud/:/mnt/user/icloudpd-/mnt/user/appdata/icloudpd-***REDACTED-user1'sInitials***
   icloudpd_user2:
      hostname: icloudpd_user2
      networks:
         icloudpd:
            aliases:
               - icloudpd_user2
      environment:
         - TZ=America/Denver
         - user==***REDACTED-user2'sAppleID***
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - icloudpd_user2_config:/mnt/user/appdata/icloudpd-/mnt/user/appdata/icloudpd-***REDACTED-user1'sInitials***
         - ./iCloud/:/mnt/user/icloudpd-/mnt/user/appdata/icloudpd-***REDACTED-user1'sInitials***
```

**Expected behaviour**
Expected Initialization to execute.

**Actual behaviour**
```
root@icloudpd_user1:/> sync-icloud.sh --Initialise
/usr/local/bin/sync-icloud.sh: line 1724: syntax error: unexpected "fi" (expecting "done")
root@icloudpd_user1:/> sync-icloud.sh
/usr/local/bin/sync-icloud.sh: line 1724: syntax error: unexpected "fi" (expecting "done")
```

**Debug log file**
no output
