### ISSUE TITLE
JPEG download directory is not mounted

### ISSUE THREAD

**Issue by beasthouse-au** [boredazfcuk/docker-icloudpd#782]
I am getting the error below when my container or process starts. Have tried removing the JPEG path (I don't think I had put this in originally), but it keeps throwing the same error. Hoping someone has an answer on how to resolve this? Also manually created the directory and same issue persists.

```
2025-03-17 02:45:22 INFO     Initialising container...
2025-03-17 02:45:22 INFO      - Create temporary files
2025-03-17 02:45:22 INFO      - Checking configuration file permissions
2025-03-17 02:45:22 INFO      - Create/update configuration file: /config/icloudpd.conf
2025-03-17 02:45:22 INFO      - Checking /config/icloudpd.conf for errors
2025-03-17 02:45:22 INFO      - Check Discord notifications configuration
2025-03-17 02:45:22 INFO      - Checing download locations are mounted
2025-03-17 02:45:22 ERROR       | JPEG download directory is not mounted: /mnt/user/photos/icloudphotos/damien/jpeg_converts
2025-03-17 02:45:22 ERROR       ! Cannot continue. Halting
```

**Comment by boredazfcuk** [comment]
You will need to make sure that your docker-compose.yaml or your docker run command mount a volume to that location: /mnt/user/photos/icloudphotos/damien/jpeg_converts

If not, you could end up with all the converted files inside the container and then they'll all be deleted when the container is upgraded.

**Comment by beasthouse-au** [comment]
Thanks @boredazfcuk - what if I do not want the converted files going to a different directory? Below is my compose if that helps narrow things down. If mounting a JPEG path, what would the container volume be for that?

```

services:
  icloudpd-damien:

    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/launcher.sh"

    container_name: "icloudpd-damien"

    environment:
      - "gotify_app_token="
      - "until_found="
      - "icloud_china="
      - "download_notifications=true"
      - "webhook_body="
      - "discord_token=[REDACTED]"
      - "name="
      - "skip_check=true"
      - "PUID=99"
      - "notification_days=7"
      - "discord_id=[REDACTED]"
      - "directory_permissions=777"
      - "webhook_id="
      - "photo_album="
      - "trigger_nextlcoudcli_synchronisation="
      - "notification_type=Discord"
      - "iyuu_token="
      - "media_id_warning="
      - "recent_only="
      - "PGID=100"
      - "HOST_CONTAINERNAME=icloudpd-damien"
      - "content_source_url="
      - "live_photo_size="
      - "command_line_options="
      - "webhook_server="
      - "media_id_startup="
      - "wecom_secret="
      - "media_id_delete="
      - "jpeg_quality="
      - "apple_id=[REDACTED]"
      - "webhook_port="
      - "wecom_proxy="
      - "file_permissions=666"
      - "gotify_server_url="
      - "skip_live_photos="
      - "jpeg_path="
      - "touser="
      - "media_id_download="
      - "auto_delete=true"
      - "notification_title=iCloudPD"
      - "pushover_token="
      - "folder_structure="
      - "authentication_type=2FA"
      - "pushover_sound=pushover"
      - "wecom_id="
      - "set_exif_datetime="
      - "skip_videos="
      - "synchronisation_delay="
      - "UMASK=000"
      - "prowl_api_key="
      - "pushover_user="
      - "convert_heic_to_jpeg=true"
      - "synchronisation_interval=43200"
      - "media_id_expiration="
      - "webhook_path="
      - "webhook_https="
      - "agentid="
      - "bark_device_key="
      - "bark_server="
      - "photo_library="
      - "TZ=Australia/Sydney"
      - "delete_notifications=true"
      - "single_pass="
      - "telegram_token="
      - "telegram_chat_id="
      - "dingtalk_token="
      - "delete_accompanying="
      - "delete_empty_directories="
      - "photo_size="
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Odin"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "XDG_DATA_HOME=/config"
      - "ENV=/etc/profile"
      - "config_file=/config/icloudpd.conf"

    hostname: "129fe5192bbb"

    image: "boredazfcuk/icloudpd"

    ipc: "private"

    labels:
      maintainer: "boredazfcuk"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/Womabre/-unraid-docker-templates/master/images/photos_icon_large.png"
      net.unraid.docker.managed: "dockerman"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    networks:
      - "odin"

    volumes:
      - "/mnt/app_cache/appdata/icloudpd-damien:/config"
      - "/mnt/user/appdata/icloudpd/root:/root"
      - "/mnt/user/photos/icloudphotos/damien:/home/user/iCloud"

    working_dir: "/"

version: "3.6"
```
